"""
SAHYOG Portal — Lawful Disclosure & Asset Freezing Notice Generator
Generates court-ready notices for LEAs targeting VASPs under:
- Section 91 CrPC (Production of Documents)
- Section 102 CrPC (Seizure of Property)
- Section 69B IT Act (Power to Collect Data)
- PMLA Section 17 (Attachment/Freeze)
"""

from datetime import datetime
from typing import Optional


def generate_notice(
    trace_result: dict,
    case_id: str,
    investigating_officer: str,
    unit: str = "Cyber Crime Police Station",
    state: str = "Maharashtra",
    notice_type: str = "FREEZE_AND_KYC",
    fir_number: Optional[str] = None,
    complainant: Optional[str] = None,
) -> dict:
    """
    Generate a lawful information disclosure and asset freezing notice.
    Returns structured dict with text notice, HTML version, and summary.
    """
    vasp = trace_result.get("nearest_vasp", {})
    vasp_name = vasp.get("name", "Unknown VASP")
    suspect_address = trace_result.get("suspect_address", "N/A")
    deposit_address = vasp.get("deposit_address", "N/A")
    deposit_amount = vasp.get("deposit_amount", "N/A")
    usd_value = vasp.get("usd_value", 0)
    inr_value = vasp.get("inr_value", 0)
    chain = trace_result.get("chain", "ETH")
    chain_name = trace_result.get("chain_name", chain)
    crime_category = trace_result.get("crime_category", "Cyber Fraud")
    risk_score = trace_result.get("composite_risk_score", 0)
    typologies = trace_result.get("detected_typologies", [])
    confidence = vasp.get("confidence", 85)
    nodal_email = vasp.get("nodal_email", "compliance@vasp.com")
    nodal_officer = vasp.get("nodal_officer", "Compliance Officer")
    legal_address = vasp.get("legal_address", "")
    freeze_authority = vasp.get("freeze_authority", "FIU-IND")

    date_str = datetime.now().strftime("%d %B %Y")
    datetime_str = datetime.now().strftime("%d/%m/%Y %H:%M IST")
    ref_no = f"SAHYOG/{case_id}/CY/{datetime.now().strftime('%Y%m%d/%H%M')}"
    fir_str = fir_number or f"FIR No. {case_id}"
    typology_list = "\n".join(
        [f"    {i+1}. {t.get('name', '')} — {t.get('ioc', '')}: {t.get('evidence', '')}"
         for i, t in enumerate(typologies)]
    ) or "    None explicitly detected in this trace"

    # ─── Build Notice Text ────────────────────────────────────────────────
    notice_text = f"""
================================================================================
    SIH26182 RESEARCH PROTOTYPE // TraceX INVESTIGATION DOSSIER
    DRAFT NOTICE FOR VASP DISCLOSURE & ASSET FREEZING [BNSS SEC 94 / CrPC SEC 91]
    ** INVESTIGATION DRAFT ONLY — REQUIRES AUTHORIZED IO APPROVAL & SIGNATURE **
================================================================================
DISCLAIMER: Generated by TraceX prototype for SIH26182 evaluation. Not an automated
legal process. Must be reviewed, signed, and authorized by a designated officer.
--------------------------------------------------------------------------------

REFERENCE NUMBER:  {ref_no}
DATE OF ISSUE:     {date_str}
CLASSIFICATION:    CONFIDENTIAL — LAW ENFORCEMENT ONLY

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TO:
    {nodal_officer}
    Compliance / AML Department
    {vasp_name}
    {legal_address}
    Email: {nodal_email}

FROM:
    {investigating_officer}
    {unit}
    {state}, India
    Through: SAHYOG Portal — Ministry of Home Affairs, Government of India

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SUBJECT: URGENT — LAWFUL INFORMATION DISCLOSURE REQUEST & DIRECTION TO
         TEMPORARILY FREEZE CRYPTOCURRENCY DEPOSIT ACCOUNT UNDER SECTION 91 CrPC
         READ WITH SECTION 69B INFORMATION TECHNOLOGY ACT, 2000 AND PREVENTION OF
         MONEY LAUNDERING ACT (PMLA), 2002

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CASE DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Case / FIR Reference:     {fir_str}
  Crime Category:           {crime_category}
  SAHYOG Case ID:           {case_id}
  Blockchain Network:       {chain_name} ({chain})
  Investigation Timestamp:  {datetime_str}
  Attribution Confidence:   {confidence}% (SAHYOG Blockchain Intelligence Engine)
  Composite Risk Score:     {risk_score}/100 [{trace_result.get('risk_category', 'HIGH')}]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SUSPECT BLOCKCHAIN EVIDENCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Suspect / Crime Origin Wallet:
  {suspect_address}

  Transaction Path (Total Hops): {trace_result.get('path_summary', {}).get('total_hops', 'N/A')}

  Nearest VASP Deposit Wallet (Your Platform):
  {deposit_address}

  Amount Deposited at Your Platform:
  {deposit_amount} (≈ USD ${usd_value:,.2f} | ₹ {inr_value:,.2f} INR)

  Amount Dissipated in Transit: {trace_result.get('path_summary', {}).get('amount_dissipated_pct', 0)}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MONEY LAUNDERING TYPOLOGIES DETECTED (FATF / FIU-IND Indicators)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{typology_list}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LEGAL AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This request is issued under the following statutory authority:

  1. Section 91 Code of Criminal Procedure (CrPC), 1973 — Summons to produce
     documents or things required for investigation.

  2. Section 69B Information Technology Act, 2000 — Power to direct any
     agency to monitor and collect traffic data or information through any
     computer resource for cybersecurity.

  3. Prevention of Money Laundering Act (PMLA), 2002, Section 17 — Authority
     to attach/freeze property believed to be proceeds of crime.

  4. Virtual Digital Assets Policy — Ministry of Finance Notification 2023
     mandating VASP reporting obligations under PMLA.

  5. FATF Recommendation 16 (Travel Rule) — VASPs are obligated to share
     originator and beneficiary information with LEAs upon lawful request.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INFORMATION SOUGHT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You are hereby directed to provide, within 48 (forty-eight) hours of receipt
of this notice, the following information pertaining to the deposit wallet
address: {deposit_address}

  A. ACCOUNT / WALLET INFORMATION
     1. Full name, date of birth, nationality of the registered account holder.
     2. Government-issued identity document (Aadhaar/PAN/Passport/Voter ID/KYC).
     3. Registered mobile number and email address.
     4. Linked bank account(s), IFSC, account number, bank name.
     5. Date of account creation.
     6. Source of funds declaration (if available).

  B. TRANSACTION RECORDS
     1. Complete transaction history for the wallet: {deposit_address}
     2. All incoming and outgoing transaction hashes.
     3. Counterparty wallet addresses for all transactions.
     4. KYC status of counterparty wallets (if available).
     5. Internal wallet-to-wallet transfers within your platform.

  C. DEVICE & ACCESS LOGS
     1. IP address(es) used to access the account.
     2. Device fingerprints (User-Agent, device ID).
     3. Login timestamps (all sessions for past 180 days).
     4. 2FA method used and mobile number for OTP.

  D. CURRENT ASSET POSITION
     1. Current balance across all wallets under this account.
     2. Any pending withdrawal requests.
     3. Any existing freeze or flag on this account.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DIRECTIONS — TEMPORARY FREEZE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You are further directed to IMMEDIATELY impose a temporary administrative debit hold (draft for review by authorized agencies)
(freeze) on the following wallet address and all associated accounts/sub-wallets
on your platform:

  TARGET WALLET:  {deposit_address}

This freeze shall:
  — Prevent any withdrawal, transfer, swap, or conversion of assets.
  — Remain in effect for a period of 30 (thirty) days pending judicial order.
  — Be extendable upon further written communication from this office.
  — Apply to ALL tokens and assets held under this account.

NOTICE TO COMPLY: Non-compliance with this request may constitute obstruction
of justice under Section 179 IPC and may attract proceedings under PMLA.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ESCALATION / FREEZING AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Freeze Authority:   {freeze_authority}

  For cross-border VASPs, this request may be escalated through:
  — INTERPOL I-24/7 National Central Bureau, New Delhi
  — MLAT (Mutual Legal Assistance Treaty) request
  — FIU-IND formal disclosure via Egmont Group Secure Web
  — MCA21 / ED (Enforcement Directorate) attachment proceedings under PMLA

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RESPONSE INSTRUCTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Please respond via:
  1. SAHYOG Portal (preferred): https://sahyog.cybercrime.gov.in
  2. Email:  [Investigating Officer email via SAHYOG secure channel]
  3. Physical: {unit}, {state}

Include Reference Number: {ref_no} in all correspondence.

This notice has been auto-generated by the SAHYOG Blockchain Intelligence &
VASP Attribution Engine and carries the same legal force as a manually issued
notice under the aforementioned statutory provisions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    {investigating_officer}
    {unit}
    {state}, India
    Issued via SAHYOG Portal | Date: {date_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[SAHYOG PORTAL — BLOCKCHAIN INTELLIGENCE ENGINE v2.0 — MHA INDIA]
[Report Hash: {__import__('hashlib').sha256(suspect_address.encode()).hexdigest()[:32]}]
================================================================================
"""

    return {
        "reference_number": ref_no,
        "vasp": vasp_name,
        "date": date_str,
        "case_id": case_id,
        "notice_text": notice_text.strip(),
        "notice_type": notice_type,
        "target_wallet": deposit_address,
        "usd_value": usd_value,
        "inr_value": inr_value,
    }
